...
...
Oh hello, I didn't mean to ignore you, I was just working on this painting.
My name is Lukan, I'm from Autumnmore, you'll probably pass it as you go through that giant door
I'll meet you there soon, and maybe again, throughout your travels. I love visiting new places and painting them.