...
...
Oh hello, I didn't mean to ignore you, I was just working on this sketch.
My name is Lukan, I'm from Autumnmore, and by the looks of it, so are you!
I haven't seen you around before, and I've lived here for a while, you must have been gone for a long time my friend.
I'll meet you back at Autumnmore after I finish this, it's just over yonder, can't miss the entrance.
It was very nice to meet you friend, oh and...
Welcome home.